#!/bin/zsh

#for ((x = 0; x < 6; x++))
#do 
	#for ((y = 0; y < 6; y++))
	#do
		#convert -size 50x50 xc:"rgb($((255 / 4.5 * $x)), $((216 / 5 * $y)), $(((255 - 8 * $y) / 2)))" avatar_$(($x * 6 + $y)).gif
	#done
#done

#for ((x = 0; x < 6; x++))
#do 
	#for ((y = 0; y < 6; y++))
	#do
		#convert avatarbase.gif -fill "rgb($((255 / 4.5 * $x)), $((216 / 5 * $y)), $(((255 - 8 * $y) / 2)))" -tint 120 avatar_$(($x * 6 + $y)).gif
	#done
#done

for ((x = 0; x < 6; x++))
do 
	for ((y = 0; y < 6; y++))
	do
		convert avatarbase.gif +level-colors "rgb($((255 / 4.5 * $x)), $((216 / 5 * $y)), $(((255 - 8 * $y) / 2)))" avatar_$(($x * 6 + $y)).gif
	done
done
